### ISSUE TITLE
Provide typings for modules

### ISSUE THREAD

**Issue by trickstival** [open-hotel/injets#5]
## The Problem
Currently modules can be instantiated like so:
```ts
// Passing an empty object to the annotation
// can become a hassle. Maybe we should create an overload that accepts 0 args, or just
// a default value equal to {} 
@Module({})
class MyModule {
  onModuleInit () {
    // more stuff here
  }
}
```

## Possible solutions
Is there any way to extend the type on the annotation, so onModuleInit would autocomplete?
Maybe we could provide an interface for the typings too, but it would require the user to import them:
```ts
import { Module, IModule } from 'injets'
@Module({})
class MyModule implements IModule {
}
```

It looks like C# though.

**Comment by salomaosnff** [comment]
Injets exports an OnModuleInit interface, just implement it.

```ts
import { Module, OnModuleInit } from 'injets'

@Module({})
class MyModule implements OnModuleInit {
  onModuleInit () {
    // your code here
  }
}
```
